version: "3.2"

services:
  lab:
    image: node:12-alpine
    restart: always
    # user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    command: tail -f
    ports:
      - 13000:3000
